# Generated by Django 6.0.2 on 2026-03-25 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=225)),
                ('experience', models.CharField(max_length=50)),
                ('proof', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.category')),
            ],
        ),
        migrations.CreateModel(
            name='CaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=200)),
                ('description', models.TextField(default='No description')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('court_location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('advocate_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.advocate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.caserequest')),
            ],
        ),
        migrations.CreateModel(
            name='Case_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField()),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.caserequest')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('court_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='court_hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('verdict', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=150)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.case_details')),
            ],
        ),
        migrations.CreateModel(
            name='CourtHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('verdict', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.caserequest')),
            ],
        ),
        migrations.CreateModel(
            name='Custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=15)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
