# Generated by Django 6.0.2 on 2026-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='email',
            field=models.EmailField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
