# Generated by Django 6.0.2 on 2026-03-27 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_court_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.category'),
        ),
    ]
