# Generated by Django 6.0.2 on 2026-03-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_caserequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserequest',
            name='blockchain_txn_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='caserequest',
            name='evidence_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
