# Generated by Django 6.0.2 on 2026-03-31 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_caserequest_blockchain_txn_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserequest',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.court'),
        ),
        migrations.AlterField(
            model_name='caserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Case Assigned To Court', 'Case Assigned To Court')], default='Pending', max_length=50),
        ),
    ]
