# Generated by Django 6.0.2 on 2026-03-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_alter_caserequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Case Assigned To Court', 'Case Assigned To Court'), ('Court Accepted', 'Court Accepted'), ('Court Rejected', 'Court Rejected'), ('Under Trial', 'Under Trial'), ('Awaiting Verdict', 'Awaiting Verdict'), ('Case Disposed', 'Case Disposed')], default='Pending', max_length=50),
        ),
    ]
