# Generated by Django 6.0.2 on 2026-04-01 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_alter_caserequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('case_file', models.FileField(blank=True, null=True, upload_to='court_cases/')),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Under Trial', 'Under Trial'), ('Closed', 'Closed')], default='Assigned', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.advocate')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.court')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_file', models.FileField(upload_to='evidence/advocate/')),
                ('description', models.TextField()),
                ('evidence_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('blockchain_txn_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.advocate')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_uploads', to='vault.caserequest')),
            ],
        ),
    ]
